version: '3.8'

services:
  zct_web:
    build:
      context: ./zct
      dockerfile: Dockerfile
    container_name: ai_coach
    ports:
      - "8080:8080"
    volumes:
      - ./zct:/zct
    environment:
      - FLASK_ENV=development
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped